### ISSUE TITLE
Kekeliruan

### ISSUE THREAD

**Issue by doelmi** [ibnujakaria/tracer-study#1]
### Page Kritik dan Saran
- [x] breadcrumb masih menampilkan tulisan "ganti password"
- [ ] avatar nggak tampil sesuai foto yang ada, masih menggunakan gambar default

### Page Detail Mahasiswa
- [x] avatar hanya tampil sebagian, seharusnya tampil penuh dengan rasio 1:1
- [x] seharusnya men-disable inputan NIM pada form edit
- [ ] halaman print juga menampilkan avatar hanya sebagian

### Page Import Excel
- [ ] tidak menampilkan kesalahan yang terjadi apabila terjadi salah data atau data ganda dll.

### Page Edit Data Mahasiswa
- [x] seharusnya men-disable inputan NIM

### Page Semua Mahasiswa
- [x] Hilangkan tombol tambah data

### Page Detail Mahasiswa
- [x] Seharusnya tombol edit dihilangkan, mahasiswa tidak dapat meng-edit data mahasiswa lain.
- [x] Seharusnya tombol print dihilangkan.

**Comment by ibnujakaria** [comment]
akeh e -_-

**Comment by ibnujakaria** [comment]
`avatar nggak tampil sesuai foto yang ada, masih menggunakan gambar default`

iku gak mbok return deh datane mahasiswa.foto

**Comment by ibnujakaria** [comment]
`tidak menampilkan kesalahan yang terjadi apabila terjadi salah data atau data ganda dll.`

iki haruse dikasih return message dari API yo... errornya apa

**Comment by doelmi** [comment]
> `avatar nggak tampil sesuai foto yang ada, masih menggunakan gambar default`
> 
> iku gak mbok return deh datane mahasiswa.foto

ga usah dikasih foto kalo gitu, tapi namanya bisa diklik nanti tampil detail mahasiswa



> `tidak menampilkan kesalahan yang terjadi apabila terjadi salah data atau data ganda dll.`
> 
> iki haruse dikasih return message dari API yo... errornya apa

coba kasih alert something wrong ae, hehe

**Comment by doelmi** [comment]
> ### Page Detail Mahasiswa
> * [x]  Seharusnya tombol edit dihilangkan, mahasiswa tidak dapat meng-edit data mahasiswa lain.
> * [x]  Seharusnya tombol print dihilangkan.

seng iki belum @ibnujakaria hud.. 

![screencapture-localhost-tracer-study-2018-11-21-13_13_55](https://user-images.githubusercontent.com/26380952/48822365-6a0ad080-ed8f-11e8-97e3-68e33286036d.png)

seharus.e tombol edit dan print dihilangkan.

**Comment by ibnujakaria** [comment]
> > ### Page Detail Mahasiswa
> > 
> > * [x]   Seharusnya tombol edit dihilangkan, mahasiswa tidak dapat meng-edit data mahasiswa lain.
> > * [x]   Seharusnya tombol print dihilangkan.
> 
> seng iki belum @ibnujakaria hud..
> 
> ![screencapture-localhost-tracer-study-2018-11-21-13_13_55](https://user-images.githubusercontent.com/26380952/48822365-6a0ad080-ed8f-11e8-97e3-68e33286036d.png)
> 
> seharus.e tombol edit dan print dihilangkan.

Lho iki haruse wes mari mi
